# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20161113_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.SlugField(unique=True)),
                ('full_name', models.CharField(max_length=1024)),
                ('about', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='portfolio/images/profile')),
            ],
        ),
    ]
