# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('caption', models.CharField(max_length=256)),
                ('link', models.URLField(blank=True)),
                ('icon', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.AddField(
            model_name='profilecontact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='portfolio.Profile'),
        ),
    ]
