# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20161117_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uri', models.SlugField(unique=True)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('cut', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='portfolio.ProjectGroup')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='portfolio/blog/files')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portfolio.Article')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
