# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-25 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20161225_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='portfolio.ArticleCategory'),
        ),
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='portfolio.ProjectGroup'),
        ),
    ]
